# Generated by Django 2.1.7 on 2019-03-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_by', models.IntegerField(blank=True, default=None, null=True)),
                ('accepted_by', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
            },
        ),
    ]
