# Generated by Django 2.1.4 on 2019-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted_by',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
